### PR TITLE
Exclude source code from text

### PR DESCRIPTION
**Pull request by mingrammer**
(#19) Exclude source code from text 
1. Exclude source code from text using regex. (catch the enclosed text with "```")
2. Add test code for excluding source code.
3. Add sample code for source code.

### CODE REVIEW

**Comment by hunkim** [comment]
Wonderful! Since this may only work for md, do you want to make a separate py file like readfile.py and implement your code there?

A main function in the file, perhaps `read_file(filename)` would return a text without source code based on the file name or something.

Once again, great job!

**Comment by mingrammer** [comment]
@hunkim I understand. You mean the file extension should be checked in `read_file(filename)`?

`````` python
...
ext = ...

if ext == 'md':
    # process with md (catch the "```" specific text)
...

# counting process
...
``````

**Comment by hunkim** [comment]
Yes. Then make them in a separate py so we may add text strippers for HTML
and other types of text files.

**Comment by mingrammer** [comment]
Review plz!

**Comment by hunkim** [comment]
Coool!

**Pull request merged**
