### PR TITLE
Output test

### PR DESCRIPTION
**Pull request by hunkim**

### CODE REVIEW

**Comment by hunkim** [comment]
@mingrammer it seems the output test fails on python3.x due to some differences in the text handling? Can you look into it?

**Comment by mingrammer** [comment]
Ok, I'll check it

**Comment by mingrammer** [comment]
@hunkim I found the problem. Yes it's about text handling differences between both versions.
In Python3, default encoding is 'utf8', so it's 'len' function counts characters in string by really 'one' character. but, that of Python2 counts the characters by 'bytes' length. for example, '한' is counted 1 in Python3, but 3 in Python2

Ye, Python3's that is really we want! So, you should modify the `sample.md` has wrong count numbers.

And **solution** is this:

```
s = myfile.read() # return 'str' type value

if type(s) == bytes: 
    s = s.decode('utf8') # for python2
```

**note that**:
In Python3: str != bytes
In Python2: str == bytes

**Comment by mingrammer** [comment]
Why .. ?

**Comment by hunkim** [comment]
I see. It's complicated. I just made this test a bit weak for now.

**Comment by mingrammer** [comment]
Can I fix that?

**Comment by hunkim** [comment]
Why? s.decode('utf8') may throw exceptions, right?

**Comment by hunkim** [comment]
> Can I fix that?
> Please! I have merged this to make it easy for you to fix.

**Comment by mingrammer** [comment]
Ye, I'll fix it.

**Comment by hunkim** [comment]
Thanks.

**Pull request merged**
